### ISSUE TITLE
Clients are intialized outside the function they are being tested

### ISSUE THREAD

**Issue by gsebil08** [marigold-dev/pollinate#3]
I'm not sure if this is a good idea to initialize the clients and their state outside of the function they're being tested in. I feel it's probably best if we spawn the clients only when they're being tested and only in the context where they're being tested. Let me know what you think.

_Originally posted by @rosalogia in https://github.com/marigold-dev/pollinate/pull/1#discussion_r822986636_

**Comment by rosalogia** [comment]
Closing this because in effect it seems to not cause any issues and is actually quite convenient
